version: '3'
services:
  players:
    image: top
    build: .
    expose:
      - '5000'
    volumes:
      - './top_players:/service'
    command: python3 service.py
    networks:
      toptennet:
        ipv4_address: 172.29.1.1
  teams:
    image: top
    build: .
    expose:
      - '5000'
    volumes:
      - './top_teams:/service'
    command: python3 service.py
    networks:
      toptennet:
        ipv4_address: 172.29.1.2
  teamsofall:
    image: top
    build: .
    expose:
      - '5000'
    volumes:
      - './top_teams_of_all_time:/service'
    command: python3 service.py
    networks:
      toptennet:
        ipv4_address: 172.29.1.3
  volatile_data_base:
    image: memcached
    hostname: data_base
    expose:
      - "11211"
    networks:
      toptennet:
        ipv4_address: 172.29.1.4
networks:
  toptennet:
    ipam:
      driver: default
      config:
        - subnet: 172.29.1.0/16